name: Execute Jest Test Suite

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with: 
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
      - run: npm install
      - name: Run Jest Suite
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINEUSER_GITHUB_TOKEN }}
