name: Execute Jest Test Suite

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: nvmrc
        name: Get the node version from the available .nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - name: Setup Node and run Jest Suite
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvmrc.outputs.node_version }}"
      - run: |
          npm install
          npm test
